---
- hosts: all
  name: Install required software
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - php-xml
    - name: Create the /var/www directory (if it doesn't already exist)
      ansible.builtin.file:
        path: /var/www
        state: directory
    - name: Create the /var/www/html directory (if it doesn't already exist)
      ansible.builtin.file:
        path: /var/www/html
        state: directory
    - name: create an ext4 filtesystem for data
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-data 
    - name: Mount my data disk under /var/www
      ansible.posix.mount:
        path: /var/www
        src: /dev/disk/by-id/google-data 
        fstype: ext4
        state: mounted
    - name: Download and unarchive Dokuwiki file
      ansible.builtin.unarchive:
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        remote_src: yes
    - name: chown/chmod -R www-data for /var/www/html file
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0775'
    - name: Download backup from GitHub
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/connormunger/cis-91/main/project2/backup.sh
        dest: /etc/cron.hourly/backup.sh
        mode: '0775'
