---
- hosts: all
  name: Add cis-91 packages/drives
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip 
          - python3-venv
          - nginx
    - name: Create the /data directory (if it doesn't already exist)
      ansible.builtin.file:
        path: /data
        state: directory
    - name: create an ext4 filtesystem for lab09
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-lab09 
    - name: Mount my lab09 disk under /data
      ansible.posix.mount:
        path: /data
        src: /dev/disk/by-id/google-lab09 
        fstype: ext4
        state: mounted
    - name: Create the /scratch directory (if it doesn't already exist)
      ansible.builtin.file:
        path: /scratch
        state: directory
    - name: create an ext4 filtesystem for local-nvme-ssd
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-local-nvme-ssd-0
    - name: Mount my local-nvme-ssd disk under /scratch
      ansible.posix.mount:
        path: /scratch
        src: /dev/disk/by-id/google-local-nvme-ssd-0
        fstype: ext4
        state: mounted
